name: Feature request
description: Suggest a change or a new feature.
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: The problem
    validations:
      required: true
  - type: textarea
    id: wanted
    attributes:
      label: What you would like
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you tried
    validations:
      required: false
